name: Step Types

on:
  workflow_dispatch:

jobs:
  say-hello-combined-step:
    runs-on: ubuntu-24.04
    steps:
      - name: Say Hello from an Inline Bash Script Step
        run: echo "Hello from an inline bash script in a GitHub Action Workflow!"
      - name: Say Hello from Python Step
        shell: python
        run: print("Hello from an inline python script in a GitHub Action Workflow!")

      - name: Say Hello from a JavaScript Marketplace Action Step
        uses: actions/hello-world-javascript-action@081a6d193d1dcb38460df1e6927486d748730f9d
        with:
          who-to-greet: "from anaction in a GitHub Action marketplace! 👋 By Marian"